# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11V2KMijzEgH-WhV0tt6pRa_q8OisSCOc

1. Reverse a String using Slice Operator
"""

s = "Alok"
rev = s[::-1]
print(rev)

"""2. Reverse a String using reversed() function"""

s = "Alok"
rev = ''.join(reversed(s))
print(rev)

"""3. Reverse a String using while loop"""

s = "Internship"
i = len(s) - 1
rev = ""

while i >= 0:
    rev += s[i]
    i -= 1

print(rev)

"""4. Reverse order of words in a string"""

s = "Coding is little hard for me"
words = s.split()
rev = ' '.join(words[::-1])
print(rev)

"""5. Reverse internal content of each word"""

s = "HTML & CSS is easy"
words = s.split()

for w in words:
    print(w[::-1], end=" ")

"""6. Merge characters of two strings alternatively"""

s1 = "DOG"
s2 = "505"
result = ""

for i in range(len(s1)):
    result += s1[i] + s2[i]

print(result)

"""7. Sort string: alphabets first, then digits"""

s = "B4A1D3"
alphabets = []
digits = []

for ch in s:
    if ch.isalpha():
        alphabets.append(ch)
    else:
        digits.append(ch)

print(''.join(sorted(alphabets) + sorted(digits)))

"""8. Remove duplicate characters from a string"""

s = "programming"
result = ""

for ch in s:
    if ch not in result:
        result += ch

print(result)

"""9. Count occurrences of each vowel"""

s = "hallucination"
vowels = "aeiou"

for v in vowels:
    print(v, ":", s.count(v))

"""10. Check whether two strings are anagrams"""

s1 = "listen"
s2 = "silent"

if sorted(s1) == sorted(s2):
    print("Anagrams")
else:
    print("Not Anagrams")