# -*- coding: utf-8 -*-
"""W1-Assignment3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w9swGZo8xzaDOJFEXPpdINpJixG0aqtW

Question:
Given a dictionary {"name": "Alex", "age": 25}, retrieve the value of key "salary" using get() and return 0 if the key does not exist.
"""

data = {"name": "Alex", "age": 25}
salary = data.get("salary", 0)
print(f"1. Salary retrieved: {salary}")

"""Question:
Write a program to print all keys from the dictionary {"a": 1, "b": 2, "c": 3}.
"""

d_keys = {"a": 1, "b": 2, "c": 3}
print(f"2. Keys: {list(d_keys.keys())}")

"""Question:
Write a program to print all values from the dictionary {"x": 10, "y": 20, "z": 30}.
"""

d_vals = {"x": 10, "y": 20, "z": 30}
print(f"3. Values: {list(d_vals.values())}")

"""
Question:
Given a dictionary {"name": "John", "age": 30}, print each key–value pair in the format key : value."""

d_items = {"name": "John", "age": 30}
print("4. Items loop:")
for key, value in d_items.items():
    print(f"   {key} : {value}")

"""
Question:
You have a dictionary {"name": "Emma", "age": 28}. Add "city": "London" and update "age" to 29 using update().
"""

emma = {"name": "Emma", "age": 28}
emma.update({"city": "London", "age": 29})
print(f"5. Updated Emma: {emma}")

"""
Question:
Given a dictionary {"a": 1, "b": 2, "c": 3}, remove the key "b" and store its value."""

d_pop = {"a": 1, "b": 2, "c": 3}
removed_val = d_pop.pop("b")
print(f"6. Popped value: {removed_val} | Remaining: {d_pop}")

"""
Question:
Write a program to remove the last inserted key–value pair from a dictionary."""

d_last = {"p": 1, "q": 2, "r": 3}
item = d_last.popitem()
print(f"7. Popped item: {item} | Remaining: {d_last}")

"""
Question:
Write a program to remove all items from a dictionary {"x": 1, "y": 2} using clear()."""

d_clear = {"x": 1, "y": 2}
d_clear.clear()
print(f"8. Cleared dictionary: {d_clear}")

"""Question:
Create a copy of the dictionary {"a": 10, "b": 20} such that changes to the copied dictionary do not affect the original.

"""

original = {"a": 10, "b": 20}
cloned = original.copy()
cloned["a"] = 99 # Changing clone doesn't touch original
print(f"9. Original: {original} | Copy: {cloned}")

"""Question:
Given a dictionary {"name": "Alice"}, use setdefault() to add the key "country" with value "India" if it does not already exist.
"""

alice = {"name": "Alice"}
alice.setdefault("country", "India")
print(f"10. Setdefault result: {alice}")

"""Question:
Create a dictionary with keys ["a", "b", "c"] and value 0 using fromkeys().

"""

new_dict = dict.fromkeys(["a", "b", "c"], 0)
print(f"11. Fromkeys dict: {new_dict}")

"""
Create a dictionary from two lists:
keys = ['a', 'b', 'c'], values = [1, 2, 3]."""

keys = ['a', 'b', 'c']
values = [1, 2, 3]
zipped_dict = dict(zip(keys, values))
print(f"12. Zipped dict: {zipped_dict}")

"""
Check if a key "salary" exists in a dictionary."""

check_dict = {"name": "Sam"}
has_salary = "salary" in check_dict
print(f"13. Does 'salary' exist? {has_salary}")

"""
Find the length of a dictionary."""

print(f"14. Length of check_dict: {len(check_dict)}")

"""
Merge two dictionaries
{'a': 1, 'b': 2} and {'c': 3, 'd': 4}."""

dict1 = {'a': 1, 'b': 2}
dict2 = {'c': 3, 'd': 4}
# Python 3.9+ Merge Operator
merged = dict1 | dict2
print(f"15. Merged dict: {merged}")