# -*- coding: utf-8 -*-
"""W1-Assignment2 .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ITg8Jf7nBUgqwX5XvvOYX0F2CtQu1VDS

1. append()

Question: Add 5, 10, 15 to an empty list
"""

lst = []
lst.append(5)
lst.append(10)
lst.append(15)
print(lst)

"""2. extend()

Question: Merge [4, 5, 6] into [1, 2, 3]
"""

list1 = [1, 2, 3]
list2 = [4, 5, 6]

list1.extend(list2)
print(list1)

"""3. insert()

Question: Insert 30 at index 2
"""

lst = [10, 20, 40, 50]
lst.insert(2, 30)
print(lst)

"""4. remove()

Question: Remove first occurrence of 2
"""

lst = [1, 2, 3, 2, 4]
lst.remove(2)
print(lst)

"""5. pop()

Question: Remove and store last element
"""

lst = [100, 200, 300, 400]
x = lst.pop()
print(x)
print(lst)

"""6. clear()

Question: Remove all elements from the list
"""

lst = [1, 2, 3, 4, 5]
lst.clear()
print(lst)

"""7. index()

Question: Find index of 'banana'
"""

lst = ['apple', 'banana', 'cherry']
print(lst.index('banana'))

"""8. count()

Question: Count occurrences of 2
"""

lst = [1, 2, 2, 3, 2, 4]
print(lst.count(2))

"""9. sort()

Question: Sort list in ascending order
"""

lst = [5, 1, 4, 2, 3]
lst.sort()
print(lst)

"""10. reverse()

Question: Reverse the list
"""

lst = [10, 20, 30, 40]
lst.reverse()
print(lst)

"""11. copy()

Question: Create an independent copy
"""

lst1 = [1, 2, 3]
lst2 = lst1.copy()

lst2.append(4)
print(lst1)
print(lst2)