# -*- coding: utf-8 -*-
"""W1-Assignment5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dU5Z90BFITOat1FZp9GogJ6rn1n5V9mA

### Create a tuple with 5 elements and print it.
"""

my_tuple = (10, 20, 30, 40, 50)
print(my_tuple)

"""### Access the 3rd element of a tuple."""

my_tuple = (10, 20, 30, 40, 50)
third_element = my_tuple[2]
print(f"The 3rd element is: {third_element}")

"""### Find the length of a tuple."""

my_tuple = (10, 20, 30, 40, 50)
tuple_length = len(my_tuple)
print(f"The length of the tuple is: {tuple_length}")

"""### Check whether an element exists in a tuple."""

my_tuple = (10, 20, 30, 40, 50)
element_to_check = 30
if element_to_check in my_tuple:
    print(f"{element_to_check} exists in the tuple.")
else:
    print(f"{element_to_check} does not exist in the tuple.")

element_to_check_2 = 99
if element_to_check_2 in my_tuple:
    print(f"{element_to_check_2} exists in the tuple.")
else:
    print(f"{element_to_check_2} does not exist in the tuple.")

"""### Convert a list into a tuple."""

my_list = [1, 2, 3, 4, 5]
tuple_from_list = tuple(my_list)
print(f"Original list: {my_list}")
print(f"Converted tuple: {tuple_from_list}")

"""### Find the maximum and minimum value in a tuple."""

my_tuple = (10, 20, 30, 40, 50)
max_value = max(my_tuple)
min_value = min(my_tuple)
print(f"Maximum value in tuple: {max_value}")
print(f"Minimum value in tuple: {min_value}")

"""### Count how many times an element appears in a tuple."""

repeated_tuple = (1, 2, 2, 3, 2, 4, 5)
count_of_2 = repeated_tuple.count(2)
print(f"Tuple: {repeated_tuple}")
print(f"The element '2' appears {count_of_2} times.")

"""### Find the index of an element in a tuple."""

my_tuple = (10, 20, 30, 40, 50)
element_to_find_index = 40
index = my_tuple.index(element_to_find_index)
print(f"The index of {element_to_find_index} is: {index}")

"""### Reverse a tuple."""

original_tuple = (1, 2, 3, 4, 5)
reversed_tuple = original_tuple[::-1]
print(f"Original tuple: {original_tuple}")
print(f"Reversed tuple: {reversed_tuple}")

"""### Slice a tuple to get the first 3 elements."""

original_tuple = (100, 200, 300, 400, 500)
first_three_elements = original_tuple[:3]
print(f"Original tuple: {original_tuple}")
print(f"First 3 elements: {first_three_elements}")