# -*- coding: utf-8 -*-
"""W1-Assignment6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oUzK-9TzJEp54BqcqxXls0aBkyZojX1T
"""

# Create a set with 5 elements
my_set = {10, 20, 30, 40, 50}
print(f"Initial set: {my_set}")

# Add an element to a set
my_set = {10, 20, 30, 40, 50}
my_set.add(60)
print(f"Set after adding 60: {my_set}")

# Remove an element from a set
my_set = {10, 20, 30, 40, 50}
my_set.remove(30)
print(f"Set after removing 30: {my_set}")

my_set.discard(100)
print(f"Set after discarding 100 (not present): {my_set}")

# Check if an element exists in a set
my_set = {10, 20, 30, 40, 50}
print(f"Does 40 exist in the set? {40 in my_set}")
print(f"Does 99 exist in the set? {99 in my_set}")

# Convert a list into a set
my_list = [1, 2, 2, 3, 4, 4, 5]
set_from_list = set(my_list)
print(f"List: {my_list}")
print(f"Set from list: {set_from_list}")

# Define two sets for subsequent operations
set1 = {1, 2, 3, 4, 5}
set2 = {4, 5, 6, 7, 8}
print(f"Set 1: {set1}")
print(f"Set 2: {set2}")

# Find the union of two sets
set1 = {1, 2, 3, 4, 5}
set2 = {4, 5, 6, 7, 8}
union_set = set1.union(set2)
print(f"Union of set1 and set2: {union_set}")

# Find the intersection of two sets
set1 = {1, 2, 3, 4, 5}
set2 = {4, 5, 6, 7, 8}
intersection_set = set1.intersection(set2)
print(f"Intersection of set1 and set2: {intersection_set}")

# Find the difference between two sets (elements in set1 but not in set2)
set1 = {1, 2, 3, 4, 5}
set2 = {4, 5, 6, 7, 8}
difference_set = set1.difference(set2)
print(f"Difference (set1 - set2): {difference_set}")

# Find the symmetric difference between two sets (elements in either set, but not in both)
set1 = {1, 2, 3, 4, 5}
set2 = {4, 5, 6, 7, 8}
symmetric_difference_set = set1.symmetric_difference(set2)
print(f"Symmetric difference of set1 and set2: {symmetric_difference_set}")

# Check if one set is a subset of another
subset1 = {1, 2}
subset2 = {1, 2, 3, 4, 5}
subset3 = {1, 6}

print(f"Is {subset1} a subset of {subset2}? {subset1.issubset(subset2)}")
print(f"Is {subset3} a subset of {subset2}? {subset3.issubset(subset2)}")

# Check if two sets are disjoint (have no common elements)
disjoint_set1 = {1, 2, 3}
disjoint_set2 = {4, 5, 6}
disjoint_set3 = {3, 7, 8}

print(f"Are {disjoint_set1} and {disjoint_set2} disjoint? {disjoint_set1.isdisjoint(disjoint_set2)}")
print(f"Are {disjoint_set1} and {disjoint_set3} disjoint? {disjoint_set1.isdisjoint(disjoint_set3)}")

# Remove duplicate elements from a list using a set
list_with_duplicates = [1, 2, 2, 3, 4, 1, 5, 3, 6]
set_without_duplicates = set(list_with_duplicates)
list_without_duplicates = list(set_without_duplicates)

print(f"Original list with duplicates: {list_with_duplicates}")
print(f"List after removing duplicates: {list_without_duplicates}")