# -*- coding: utf-8 -*-
"""W1-Assignment4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UTrGtl4SlI_a-b9-LmCdw4ZoRAtPVs8K
"""

# Write a function to find the square of a number.
def find_square(number):
    return number * number

print(f"The square of 5 is: {find_square(5)}")
print(f"The square of 10 is: {find_square(10)}")

# Write a function that returns the maximum of two numbers.
def find_maximum(num1, num2):
    return max(num1, num2)

print(f"The maximum of 7 and 3 is: {find_maximum(7, 3)}")
print(f"The maximum of 12 and 20 is: {find_maximum(12, 20)}")

# Write a function to check if a number is prime.
def is_prime(number):
    if number < 2:
        return False
    for i in range(2, int(number**0.5) + 1):
        if number % i == 0:
            return False
    return True
print(f"Is 7 prime? {is_prime(7)}")
print(f"Is 10 prime? {is_prime(10)}")
print(f"Is 2 prime? {is_prime(2)}")
print(f"Is 1 prime? {is_prime(1)}")

# Write a function to calculate factorial of a number.
def calculate_factorial(number):
    if number < 0:
        return "Factorial is not defined for negative numbers"
    elif number == 0:
        return 1
    else:
        factorial = 1
        for i in range(1, number + 1):
            factorial *= i
        return factorial

print(f"Factorial of 5 is: {calculate_factorial(5)}")
print(f"Factorial of 0 is: {calculate_factorial(0)}")
print(f"Factorial of -3 is: {calculate_factorial(-3)}")

# Write a function to reverse a string.
def reverse_string(s):
    return s[::-1]

print(f"Reversed 'hello': {reverse_string('hello')}")
print(f"Reversed 'Python': {reverse_string('Python')}")

# Write a function that takes two positional arguments and returns their sum.
def sum_two_numbers(a, b):
    return a + b

print(f"Sum of 10 and 20: {sum_two_numbers(10, 20)}")

# Write a function that takes name and age and prints them using keyword arguments.
def print_person_details(name, age):
    print(f"Name: {name}, Age: {age}")

print_person_details(name="Alice", age=30)
print_person_details(age=25, name="Bob")

# Write a function where passing arguments in the wrong order gives a different output.
def concatenate_strings(str1, str2):
    return str1 + str2

print(f"Order 1: {concatenate_strings('Hello', 'World')}")
print(f"Order 2: {concatenate_strings('World', 'Hello')}")

def subtract_numbers(num1, num2):
    return num1 - num2

print(f"Order 1 (subtraction): {subtract_numbers(10, 5)}")
print(f"Order 2 (subtraction): {subtract_numbers(5, 10)}")

# Write a function to calculate the area of a rectangle using keyword arguments.
def calculate_rectangle_area(length, width):
    return length * width
print(f"Area of rectangle (length=5, width=4): {calculate_rectangle_area(length=5, width=4)}")
print(f"Area of rectangle (width=6, length=3): {calculate_rectangle_area(width=6, length=3)}")

# Write a function to calculate simple interest with default rate = 5%.
def calculate_simple_interest(principal, time, rate=0.05):
    return principal * time * rate

print(f"Simple interest for P=1000, T=2 years (default rate): {calculate_simple_interest(1000, 2)}")
print(f"Simple interest for P=1000, T=2 years, R=7%: {calculate_simple_interest(1000, 2, 0.07)}")

# Write a function to calculate power of a number with default exponent = 2.
def calculate_power(base, exponent=2):
    return base ** exponent

print(f"5 to the power of 2 (default exponent): {calculate_power(5)}")
print(f"5 to the power of 3: {calculate_power(5, 3)}")

# Write a function to append an element to a list using a default parameter.
def append_to_list(element, target_list=[]):
    target_list.append(element)
    return target_list

list1 = append_to_list(10)
print(f"List after appending 10: {list1}")

list2 = append_to_list(20)
print(f"List after appending 20: {list2}")
def safe_append_to_list(element, target_list=None):
    if target_list is None:
        target_list = []
    target_list.append(element)
    return target_list

print(f"\nUsing safe_append_to_list:")
safe_list1 = safe_append_to_list(100)
print(f"Safe List after appending 100: {safe_list1}")
safe_list2 = safe_append_to_list(200)
print(f"Safe List after appending 200: {safe_list2}")
safe_list3 = safe_append_to_list(300, ['existing'])
print(f"Safe List after appending 300 to existing list: {safe_list3}")

# Write a function that demonstrates the issue with mutable default arguments.
def add_to_list(item, my_list=[]):
    my_list.append(item)
    return my_list

print(f"First call: {add_to_list(1)}")
print(f"Second call: {add_to_list(2)}")
print(f"Third call: {add_to_list(3)}")

# Write a function that accepts any number of integers and returns their sum.
def sum_all_integers(*numbers):
    total = 0
    for num in numbers:
        if isinstance(num, int):
            total += num
        else:
            print(f"Warning: '{num}' is not an integer and will be skipped.")
    return total

print(f"Sum of (1, 2, 3): {sum_all_integers(1, 2, 3)}")
print(f"Sum of (10, 20, 30, 40): {sum_all_integers(10, 20, 30, 40)}")
print(f"Sum of (5, 'a', 15): {sum_all_integers(5, 'a', 15)}") # With non-integer

# Write a function that accepts any number of numbers and returns the maximum.
def find_max_of_numbers(*numbers):
    if not numbers:
        return None
    return max(numbers)

print(f"Max of (1, 5, 2, 8, 3): {find_max_of_numbers(1, 5, 2, 8, 3)}")
print(f"Max of (100, 20): {find_max_of_numbers(100, 20)}")
print(f"Max of no numbers: {find_max_of_numbers()}")

# Write a function that multiplies all numbers passed using *args.
def multiply_all_numbers(*numbers):
    if not numbers:
        return 1
    product = 1
    for num in numbers:
        product *= num
    return product

print(f"Product of (1, 2, 3, 4): {multiply_all_numbers(1, 2, 3, 4)}")
print(f"Product of (5, 0, 10): {multiply_all_numbers(5, 0, 10)}")
print(f"Product of no numbers: {multiply_all_numbers()}")

# Write a function that counts how many arguments were passed.
def count_arguments(*args):
    return len(args)

print(f"Number of arguments: {count_arguments(1, 2, 3, 'hello', True)}")
print(f"Number of arguments: {count_arguments('a', 'b')}")
print(f"Number of arguments: {count_arguments()}")

# Write a function that prints all key–value pairs passed using **kwargs.
def print_kwargs(**kwargs):
    for key, value in kwargs.items():
        print(f"{key}: {value}")

print("Details 1:")
print_kwargs(name="Alice", age=30, city="New York")
print("\nDetails 2:")
print_kwargs(product="Laptop", price=1200)

# Write a function that accepts student details and prints them neatly.
def print_student_details(**details):
    print("--- Student Details ---")
    for key, value in details.items():
        print(f"{key.replace('_', ' ').title()}: {value}")
    print("-----------------------")

print_student_details(name="John Doe", student_id="S12345", major="Computer Science", gpa=3.8)
print("\n")
print_student_details(name="Jane Smith", age=20, course="Mathematics")

# Write a function that calculates total marks using values from **kwargs.
def calculate_total_marks(**subjects_marks):
    total = 0
    for subject, marks in subjects_marks.items():
        if isinstance(marks, (int, float)):
            total += marks
        else:
            print(f"Warning: Marks for {subject} ('{marks}') is not a valid number and will be skipped.")
    return total

student_marks1 = {"Math": 90, "Science": 85, "English": 78}
print(f"Total marks for student 1: {calculate_total_marks(**student_marks1)}")

student_marks2 = {"History": 70, "Geography": 65, "Art": "Absent"}
print(f"Total marks for student 2: {calculate_total_marks(**student_marks2)}")

# Write a function that accepts two numbers as positional-only arguments and returns their difference.

def subtract_positional_only(a, b, /):
    return a - b

print(f"Difference of 10 and 5: {subtract_positional_only(10, 5)}")

try:
    subtract_positional_only(a=10, b=5)
except TypeError as e:
    print(f"Error attempting to use keyword arguments: {e}")

# Write a function that calculates division using positional-only arguments.
def divide_positional_only(dividend, divisor, /):
    if divisor == 0:
        raise ValueError("Divisor cannot be zero")
    return dividend / divisor

print(f"10 divided by 2: {divide_positional_only(10, 2)}")

try:
    print(f"10 divided by 0: {divide_positional_only(10, 0)}")
except ValueError as e:
    print(f"Error during division: {e}")

try:
    divide_positional_only(dividend=10, divisor=2)
except TypeError as e:
    print(f"Error attempting to use keyword arguments: {e}")

# Write a function where operation must be passed as a keyword-only argument.
def perform_calculation(num1, num2, *, operation):
    if operation == 'add':
        return num1 + num2
    elif operation == 'subtract':
        return num1 - num2
    elif operation == 'multiply':
        return num1 * num2
    elif operation == 'divide':
        if num2 == 0:
            raise ValueError("Cannot divide by zero")
        return num1 / num2
    else:
        raise ValueError("Invalid operation")

print(f"10 + 5: {perform_calculation(10, 5, operation='add')}")
print(f"10 - 5: {perform_calculation(10, 5, operation='subtract')}")

try:
    perform_calculation(10, 5, 'add')
except TypeError as e:
    print(f"Error attempting to use positional argument for operation: {e}")

# Write a function that calculates salary where bonus must be keyword-only.
def calculate_salary(base_salary, *, bonus=0):
    return base_salary + bonus

print(f"Salary with no bonus: {calculate_salary(50000)}")
print(f"Salary with bonus: {calculate_salary(60000, bonus=5000)}")

try:
    calculate_salary(70000, 2000)
except TypeError as e:
    print(f"Error attempting to use positional argument for bonus: {e}")

# Write a function that demonstrates a mix of positional-only, positional-or-keyword, keyword-only, and variable arguments.
def complex_function(a, b, /, c, d=10, *args, e, **kwargs):
    print(f"Positional-only: a={a}, b={b}")
    print(f"Positional-or-keyword: c={c}, d={d}")
    print(f"Variable positional (*args): {args}")
    print(f"Keyword-only: e={e}")
    print(f"Variable keyword (**kwargs): {kwargs}")
    total_sum = a + b + c + d + sum(args) + e
    for value in kwargs.values():
        if isinstance(value, (int, float)):
            total_sum += value
    print(f"Calculated total sum: {total_sum}")

print("\n--- Test Case 1 ---")
complex_function(1, 2, 3, e=4, f=5, g=6)

print("\n--- Test Case 2 (with *args and d overridden) ---")
complex_function(10, 20, 30, 50, 60, e=70, name="Python", version=3.9)

print("\n--- Test Case 3 (minimum arguments) ---")
complex_function(100, 200, 300, e=400)

try:
    print("\n--- Test Case 4 (Error: positional-only as keyword) ---")
    complex_function(a=1, b=2, c=3, e=4)
except TypeError as ex:
    print(f"Expected Error: {ex}")

try:
    print("\n--- Test Case 5 (Error: keyword-only as positional) ---")
    complex_function(1, 2, 3, 4)
except TypeError as ex:
    print(f"Expected Error: {ex}")